name: TempExempt
version: "${project.version}"
main: net.earthmc.tempexempt.TempExempt
api-version: "1.19"
folia-supported: true
authors: [Fruitloopins]
description: Temporarily exempt players from Grim anticheat for evidence gathering
website: https://earthmc.net
depend:
  - LuckPerms

commands:
  tempexempt:
    description: "Temporarily exempt a player from Grim anticheat"
    usage: "/tempexempt {username}"
    permission: "tempexempt.command.tempexempt"

permissions:
  tempexempt.command.tempexempt:
    description: "Grants permission to temporarily exempt a player from Grim anticheat"
    default: false
